{
    "token": 'H8c9k93tUXyCW9X6Ee3PfMv9703c5KBHQe0LrPQWM2PVnvK3GywSs0qbCwVlwUhLaFaIEI19xD_AlSBiFH55lVnTR-Qw5xNuDtaIOT0XCGhSfEiQfKmvmm88',
    "study_id": '687a341c9809214e6d7f877f',
    "max_concurrent_sessions": 3,
    "workload_checker_period": 60
}